Update dependencies and eslint config and changes
FutureNorthants/northants-website pull request #254
Opened 2022-01-26 09:55 UTC by chrisrhymes

- Update npm dependencies
- Migrate html-react-parser to [v1](https://github.com/remarkablemark/html-react-parser#v100)
- Update prettier to v8 - no longer required to extend all [prettier plugins](https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21)
- Remove function blocks and unneeded react fragments to make eslint happy

2022-01-26 10:06 UTC, chrisrhymes commented on frontend/src/pages/rss/[filename].tsx
> +/* eslint-disable react/function-component-definition */
Next.js wouldn't compile if the default export [wasn't a valid React Component](https://nextjs.org/docs/messages/page-without-valid-component)

2022-01-26 10:06 UTC, chrisrhymes commented on frontend/src/pages/sitemap.xml.tsx
> +/* eslint-disable react/function-component-definition */
Next.js wouldn't compile if the default export [wasn't a valid React Component](https://nextjs.org/docs/messages/page-without-valid-component)

2022-01-26 10:25 UTC, DamienBurkeWN requested changes
Sorry but I feel complying with the new linter rules produces much less readable code here. Particularly dislike the lack of explicit returns.

2022-01-26 10:25 UTC, DamienBurkeWN commented on frontend/src/components/AlertBannerService/index.tsx
> -const AlertBannerServiceIE = (): ReactElement | null => {
This might keep a linter happy but I feel it's making the code a lot less readable. I'd rather we turned off the linter rule in question.

2022-01-26 10:25 UTC, DamienBurkeWN commented on frontend/src/components/TextWithSlices/index.tsx
> +const transformAccordion = (accordion: Accordion_sections): AccordionSectionProps => ({
Absolutely the same objection here, readability. What's clearer - () around the function definition or 'return xxx' within it. I think the implicit return syntax is horrible, and can lead to difficult to spot bugs if the brackets are omitted.

2022-01-26 10:25 UTC, DamienBurkeWN commented on frontend/src/components/TextWithSlices/index.tsx
> +      return <p />; // should never happen
Bit uncomfortable with this one too. `<></>` is relatively explicit that no actual element is being returned, this changes behaviour to come back with an empty paragraph. Which linter rule objected? Be good to know why it was considered poor form, as we're seeing so many rules that aren't great.

2022-01-26 10:25 UTC, DamienBurkeWN commented on frontend/src/components/TextWithSlices/index.tsx
> +function TextWithSlices({ html, embeds }: TextWithSlicesProps | AccordionEmbedProps): ReactElement {
Nice to see one going the other way ;)

There's an interesting discussion here: https://softwareengineering.stackexchange.com/questions/364086/why-use-const-foo-instead-of-function-foo

Javascript really is a mess of stuff but I'm leaning towards explicit use of functions rather than arrow functions now.

2022-01-26 14:34 UTC, chrisrhymes commented on frontend/src/components/TextWithSlices/index.tsx
> +      return <p />; // should never happen
I think it was this rule it was flagging. `Fragments should contain more than one child - otherwise, there‘s no need for a Fragment at all.`. You are right, it's changing behaviour. I will revert this and eslint-disable here.

2022-01-26 15:20 UTC, chrisrhymes commented on frontend/.eslintrc.js
>    rules: {
- The rules have been reordered alphabetically as they were a bit all over the place. 
- Disabled the arrow-body-style to disable the need for implicit return
- It also seems the jsx-a11y rules now work with the Next.js <Link> component so they have been removed.

2022-01-27 09:33 UTC, DamienBurkeWN requested changes

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/lib/generateRssFeed.ts
> +    .then((queryRes) => queryRes.data.news_feed_latest)
Still got the implicit returns here

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/lib/generateRssFeed.ts
> +    .catch(() => null);
...and here

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/lib/getSearchSuggestions.ts
> +       [] // if we failed to get suggestions, it's not the end of the world
...and here

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/lib/getSearchSuggestions.ts
> +    pageTitlesOnly = pageTitles.map((item: GetPageTitles_page_titles) => item.title);
...and here

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/pages/_app.tsx
> +    .then((res) => res.data.globals);
...and here

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/pages/news.tsx
> +    .then((queryRes) => ({
...and here

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/pages/rss/[filename].tsx
> +  <ErrorPage errorCode="503" pageTitle="Syndication feed generation failed or file type unsupported" />
...and here

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/pages/search.tsx
> +      props: { ...queryRes, suggestions: searchSuggestions },
...and here

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/pages/sitemap.xml.tsx
> +const Sitemap = (): ReactElement => <div>Sitemap</div>;
...and here

2022-01-27 09:33 UTC, DamienBurkeWN commented on frontend/src/types/utils.ts
> +): obj is Extract<T, { __typename: N }> => obj.__typename === typename;
...and here

2022-01-27 16:51 UTC, DamienBurkeWN approved these changes
👍

2022-01-31 10:47 UTC, merged