Feature/summary backend
FutureNorthants/northants-website pull request #258
Opened 2022-01-27 11:59 UTC by chrisrhymes

Add the ability to choose to show the page summary.

- checkout branch then `./drush.wrapper @docker config:import` 
- Try out the below query for a service page and a service landing page. It should return `false` for the showSummary. 
- Edit the pages and check the `Show Summary` tickbox below the `Summary` textbox, publishing the pages. 
- Run the query again and ensure the showSummary now returns `true`

```graphql
{
  route(path: "/the-path-to-test") {
    __typename
    ... on DrupalNodeRoute {
      node {
        ... on ServicePageNode {
          __typename
          title
          summary
          showSummary
        }
         ... on ServiceLandingPageNode {
          __typename
          title
          summary
          showSummary
        }
      }
    }
  }
}
```

2022-01-27 12:08 UTC, chrisrhymes commented on backend/src/config/sync/core.entity_form_display.node.service_landing_page.default.yml
> +      region: content
Not sure why this was set to hidden?

2022-01-27 16:52 UTC, DamienBurkeWN commented on backend/src/config/sync/core.entity_form_display.node.service_landing_page.default.yml
> +      region: content
Beats me!

2022-01-27 17:08 UTC, DamienBurkeWN requested changes
Couple of unnecessary ternaries and I've messaged you a suggestion for improving the page view display.

2022-01-28 16:18 UTC, DamienBurkeWN approved these changes

2022-01-31 10:54 UTC, DamienBurkeWN approved these changes

2022-01-31 10:54 UTC, merged