Backend support for Promotions slice
FutureNorthants/northants-website pull request #286
Opened 2022-02-04 16:03 UTC by DamienBurkeWN

### Setup
Checkout this branch and run a `./drush.wrapper @docker config:import` and `cache:rebuild`

### Testing
1. Verify that you can now insert a promotions slice in the body of any page and add up to 4 promotional tiles within the slice. TODO: need a slice icon from Lawrence.
2. Go to https://core-cms.northants.localhost/graphql and enter the following query:
```graphql
{
  route(path: "your-page-route") {
    node {
      title
      body {
        value
        embeds {
          id
          paragraph {
            ... on PromotionsParagraph {
              promotions {
                id
                imageLarge
                imageMedium
                imageSmall
                imageAltText
                title
                body {
                  value
                }
                link {
                  title
                  url
                }
              }
            }
          }
        }
      }
    }
  }
}
```
...and verify it includes the data you expect.

2022-02-04 16:04 UTC, DamienBurkeWN commented on backend/src/themes/nc_seven/css/ckeditor.css
> -.paragraph--type--file-download {
Moved to the appropriate file and other unused stuff removed

2022-02-04 16:09 UTC, DamienBurkeWN commented on backend/src/themes/nc_seven/css/ckeditor.css
> + * To add further styles for custom paragraphs etc. create files in the ckeditor folder
Kind of a reminder to myself next time I'm doing this 🤣

2022-02-04 16:09 UTC, DamienBurkeWN commented on backend/src/themes/nc_seven/css/ckeditor.css
> -/* Gallery slice styles */
No such slice...

2022-02-04 16:09 UTC, DamienBurkeWN commented on backend/src/themes/nc_seven/css/ckeditor.css
> -/* Lead paragraph slice styles */
No such slice...

2022-02-04 16:09 UTC, DamienBurkeWN commented on backend/src/themes/nc_seven/css/ckeditor.css
> -.paragraph--type--newsletter-signup {
From a module that we don't use...

2022-02-08 09:22 UTC, chrisrhymes requested changes
Shouldn't there be config changes in yaml files to allow the new slice in the editor?

2022-02-08 09:22 UTC, chrisrhymes commented on backend/src/themes/nc_seven/css/ckeditor/paragraph--promotions.css
> +/* Display promotions area vaguely like its final output */
As this isn't prefixed with .paragraph--type--promotions, should this be in a general CSS file rather than a specific paragraph file?

2022-02-08 10:11 UTC, DamienBurkeWN commented
It was a Friday afternoon man...

2022-02-09 13:49 UTC, chrisrhymes submitted a review, later dismissed
👍

2022-02-09 16:50 UTC, chrisrhymes approved these changes
Only slight change you could do is the paragraph video icon css is now out of order, with the addition of the image-slice icon. Other than that all looks good.

2022-02-09 17:01 UTC, merged