Frontend support for GoogleMap slice
FutureNorthants/northants-website pull request #302
Opened 2022-02-15 10:07 UTC by DamienBurkeWN

2022-02-15 14:28 UTC, DamienBurkeWN commented on frontend/src/components/TextWithSlices/index.tsx
> +  const processed = parse(html || '', {
I'm not sure what's caused this but it appears html is null on the homepage when this is first called, this fixes it. Doesn't appear to be anything missing and I spent far too long trying to figure out why it was happening...

2022-02-16 08:45 UTC, chrisrhymes requested changes
Just need to change the way the PromoBody is passed into the Homepage and MemorialHomepage, then should be able to revert the change in TextWithSlices for the html parse.

2022-02-16 08:45 UTC, chrisrhymes commented on frontend/src/components/TextWithSlices/index.tsx
> +  const processed = parse(html || '', {
The PromoBanner body content is not being displayed on the home page after the backend update. The PromoBlock text is displayed ok. 

The body is a string now rather than an object so `pages/[...path]/index.tsx` needs to be updated to pass in the body, rather than the `body.value` for the Homepage and the MemorialHomepage. 

```js
{ html: promoBanner[0].body.value, embeds: [] }

// Change to
{ html: promoBanner[0].body, embeds: [] }
```

2022-02-16 09:38 UTC, DamienBurkeWN commented on frontend/src/components/TextWithSlices/index.tsx
> +  const processed = parse(html || '', {
![image](https://user-images.githubusercontent.com/91884003/154237042-cd591e80-501e-403c-b063-04c8722312b8.png)

2022-02-16 13:41 UTC, chrisrhymes approved these changes
👍

2022-02-16 14:20 UTC, merged