Add TLS check
FutureNorthants/northants-website pull request #319
Opened 2022-02-21 15:21 UTC by DamienBurkeWN

### Testing

- Checkout this branch, `yarn install && yarn dev`
- View any page, should be no changes
- Now edit the `src/lib/tlsChecker.ts` file to change the TLS_CHECK_URL to anything else and refresh the page, expect a warning banner
- Back out your changes. Edit your env.local to set TLS_CHECK_URL to an empty string. Refresh the page, expect no warning banner.

2022-02-21 15:22 UTC, DamienBurkeWN commented on frontend/package.json
> +    "@graphql-codegen/cli": "2.4.0",
These haven't changed, just moved for no good reason at all. Thanks yarn.

2022-02-21 15:24 UTC, DamienBurkeWN commented on frontend/src/lib/tlsChecker.ts
> +  const tlsCheckURL = process.env.TLS_CHECK_URL ? process.env.TLS_CHECK_URL : 'https://tls-checker.s3.eu-west-2.amazonaws.com/tlscheck.json';
The file at this URL is a bit of json:
```json
{"if_you_can_see_this_your_browser_is_ok":1}
```

2022-02-21 16:49 UTC, chrisrhymes requested changes
Not sure about this if we can't display the banner to all of the users that need to see it?

2022-02-21 16:49 UTC, chrisrhymes commented on frontend/src/components/AlertBannerService/index.tsx
> +          It looks like you are using an out of date version of{' '}
Might read better if it said, 'It looks like you are using an out of date browser which is not capable of using TLS 1.3...'

2022-02-21 16:49 UTC, chrisrhymes commented on frontend/src/lib/tlsChecker.ts
> +  const tlsCheckURL = process.env.TLS_CHECK_URL ? process.env.TLS_CHECK_URL : 'https://tls-checker.s3.eu-west-2.amazonaws.com/tlscheck.json';
According to this, IE11 and Legacy Edge support TLS 1.2 so they won't see the banner? https://caniuse.com/tls1-2

2022-02-22 09:52 UTC, DamienBurkeWN commented on frontend/src/lib/tlsChecker.ts
> +  const tlsCheckURL = process.env.TLS_CHECK_URL ? process.env.TLS_CHECK_URL : 'https://tls-checker.s3.eu-west-2.amazonaws.com/tlscheck.json';
Yes, the intention is this file will be 1.3 only. It is _currently_ 1.2 only as AWS doesn't seem to be applying 1.3 limits correctly and Kev is on the case.

2022-02-22 09:53 UTC, DamienBurkeWN commented on frontend/src/lib/tlsChecker.ts
> +  const tlsCheckURL = process.env.TLS_CHECK_URL ? process.env.TLS_CHECK_URL : 'https://tls-checker.s3.eu-west-2.amazonaws.com/tlscheck.json';
(this is also why the URL can be overridden via environment variable in case we can't use the S3 bucket for this)

2022-02-22 09:57 UTC, chrisrhymes commented on frontend/src/lib/tlsChecker.ts
> +  const tlsCheckURL = process.env.TLS_CHECK_URL ? process.env.TLS_CHECK_URL : 'https://tls-checker.s3.eu-west-2.amazonaws.com/tlscheck.json';
Ok, thanks for clearing that up.

2022-02-22 10:18 UTC, chrisrhymes approved these changes

2022-04-05 13:37 UTC, DamienBurkeWN commented
Looks like this is not going to get used

2022-04-05 13:37 UTC, closed without merging