Return redirect if path begins with /node/
FutureNorthants/northants-website pull request #327
Opened 2022-02-28 16:59 UTC by chrisrhymes

Check if the path begins with `/node/` and return a DrupalRedirectRoute with the alias set as the destination. 

Additionally check that there is an alias set or that the alias is not the same as the path, otherwise it could cause a redirect loop. 

## To Test

- View a page in the CMS and make note of the url
- Press edit on a page in the CMS and then make note of the node id in the url
- Use the below graphql query and replace the 169 with the node id
- Ensure that the destination matches the url in the view page in the CMS
- Load the '/node/169' url (or whatever you have tested) in the frontend and it should be redirected to the destination

```graphql
{
  route(path: "/node/169") {
    __typename
    ... on DrupalRedirectRoute {
       __typename
      destination
      status
    }
  }
}
```

2022-03-01 09:12 UTC, chrisrhymes commented on backend/src/modules/nc_graphql/src/Root.php
> +
You can't seem to set the homepage alias to `/` in Drupal, it makes it blank. This if statement catches if the node type is homepage and then redirects to the root.

2022-03-01 09:13 UTC, chrisrhymes commented on backend/src/modules/nc_graphql/src/Root.php
> +
This if statement should catch all other `/node/id` paths and provide a redirect to the alias, unless there isn't an alias set.

2022-03-09 12:53 UTC, DamienBurkeWN requested changes
Works well for existing nodes. However, if you give it a node ID that doesn't exist (4 on my DB for instance), it bombs out hard and the frontend errors as a result rather than giving a 404

2022-03-10 13:26 UTC, chrisrhymes commented on backend/src/modules/nc_graphql/src/Root.php
> +        } catch (Exception $e) {
I have added another catch for generic exception which returns a DrupalNotFoundRoute so the frontend should show a 404 in this case.

2022-03-10 13:47 UTC, DamienBurkeWN approved these changes
Perfick 👍

2022-03-10 13:56 UTC, merged